{
 "title": "F1Race",
 "time": { "from": "now-10m", "to": "now-30s" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Drivers",
    "label": "driver",
    "query": "from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lastLapTime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"LastLapTime\")\r\n  |> group(columns: [\"driver\"])\r\n  |> distinct(column: \"driver\")\r\n  |> keep(columns: [\"_value\"])"
   }
  ]
 },
 "panels": [
  {
   "title": "Standing",
   "type": "table",
   "gridPos": { "h": 21, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "time:s.SSS" } },
   "targets": [
    {
     "query": "gapData = from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gapToLeader\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"GapToLeader\")\r\n  |> last()\r\n  |> group()\r\n  |> keep(columns: [\"driver\", \"_value\"])\r\n  \r\nintervalData = from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"intervalToPositionAhead\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"IntervalToPositionAhead\")\r\n  |> last()\r\n  |> group()\r\n  |> keep(columns: [\"driver\", \"_value\"])\r\n\r\nlastLapData = from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lastLapTime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"LastLapTime\")\r\n  |> last()\r\n  |> group()\r\n  |> keep(columns: [\"driver\", \"_value\"])\r\n  \r\njoin(\r\n    tables: {gap:gapData, interval:intervalData},\r\n    on: [\"driver\"],\r\n) |> sort(columns: [\"_value_gap\"])\r\n  |> fill(column: \"position\", value: 1.0)\r\n  |> cumulativeSum(columns: [\"position\"])\r\n  |> map(fn: (r) => ({ r with gap: r._value_gap * 1000.0 }))\r\n  |> map(fn: (r) => ({ r with interval: r._value_interval * 1000.0 }))"
    }
   ]
  },
  {
   "title": "Lap time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lastLapTime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"LastLapTime\")\r\n  |> filter(fn: (r) => r[\"driver\"] =~ /${Drivers:regex}/)"
    }
   ]
  },
  {
   "title": "Race control messages",
   "type": "logs",
   "gridPos": { "h": 13, "w": 11, "x": 5, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"raceControlMessage\")"
    }
   ]
  },
  {
   "title": "Last top speed",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"speedTrap\")\n  |> filter(fn: (r) => r[\"driver\"] =~ /${Drivers:regex}/)"
    }
   ]
  },
  {
   "title": "Weather data",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weatherData\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"AirTemp\"  or r[\"_field\"] == \"TrackTemp\" or r[\"_field\"] == \"WindSpeed\" or r[\"_field\"] == \"Rainfall\")"
    }
   ]
  },
  {
   "title": "Standing Test",
   "type": "table",
   "gridPos": { "h": 21, "w": 5, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "time:s.SSS" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lastLapTime\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"LastLapTime\")\r\n  |> last()\r\n  |> group()\r\n  |> keep(columns: [\"driver\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Gap To Leader",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gapToLeader\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"GapToLeader\")\r\n  |> filter(fn: (r) => r[\"driver\"] =~ /${Drivers:regex}/)"
    }
   ]
  }
 ]
}